### ISSUE TITLE
[Develop] Response for branch return wrong format

### ISSUE THREAD

**Issue by ignaciomolina** [SmartDeveloperHub/gitlab-collector#12]
The endpoint for an specific branch response with:

{
  "name": "add-bower",
  "contributors": "['6665726E616E646F2E736572656E614063656E7465726F70656E6D6964646C65776172652E636F6D', '786166696C6F7840676D61696C2E636F6D', '616C656A34666340676D61696C2E636F6D']"
}

The "contributors" value should be a list of IDs, not a String representation of a Python list

**Comment by alejandrofcarrera** [comment]
Example of fixed branch:
{"name": "master", "contributors": ["616C656A34666340676D61696C2E636F6D"]}
