### ISSUE TITLE
GitCollector not expect "description" field for project information

### ISSUE THREAD

**Issue by ignaciomolina** [SmartDeveloperHub/gitlab-collector#3]
GitCollector not expect "description" field for project information which cause an interruption on the project parsing data

**Comment by alejandrofcarrera** [comment]
Description was not a valid field. So, it was improved to allow it and this bug has been fixed for next version or other future fields.

**Comment by alejandrofcarrera** [comment]
Branch bug-project-description-field merged and issue fixed.
