### ISSUE TITLE
Collector stops after exception due to not expected commit format

### ISSUE THREAD

**Issue by ignaciomolina** [SmartDeveloperHub/gitlab-collector#7]
When the commit author name has more than one word, GitCollector takes the name's second word as a date (long), which raises a ValueError exception and stops Collector Task.

Example:
> Luca-Bogdan Grigorescu 1447541058
> 8 files changed, 10 insertions(+), 10 deletions(-)

> ValueError: invalid literal for long() with base 10: 'Grigorescu'

Has been used the following repository: https://github.com/docker/docker.git

**Comment by alejandrofcarrera** [comment]
Final report for docker/docker.git :
3 B:   0 - |   3 +
21590 C:   0 - | 21590 +
23299 C:   0 - | 23299 +
23553 C:   0 - | 23553 +
